name: dito_sdk
description: Plugin Flutter para integração com o CRM Dito, fornecendo APIs unificadas para iOS e Android
version: 3.0.1
homepage: https://github.com/ditointernet/dito_sdk_flutter

environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

workspace:
  - example

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  melos: ^7.0.0


flutter:
  plugin:
    platforms:
      android:
        package: br.com.dito.ditosdk
        pluginClass: DitoSdkPlugin
      ios:
        pluginClass: DitoSdkPlugin
